//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MId { get; set; }
        public string MemberName { get; set; }
        public string MemberAge { get; set; }
        public int CustomerId { get; set; }
        public decimal TicketCost { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
